apiVersion: v1
kind: Service
metadata:
  name: project-c-service
spec:
  type: NodePort
  selector:
    app: project-c
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30003

